services:

  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: cinema_cluster
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    hostname: cassandra2
    depends_on:
      - cassandra1
    environment:
      CASSANDRA_CLUSTER_NAME: cinema_cluster
      CASSANDRA_SEEDS: cassandra1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M

  cassandra3:
    image: cassandra:4.1
    container_name: cassandra3
    hostname: cassandra3
    depends_on:
      - cassandra1
    environment:
      CASSANDRA_CLUSTER_NAME: cinema_cluster
      CASSANDRA_SEEDS: cassandra1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M